//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SVR_USER
    {
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> COMPANY_ID { get; set; }
        public Nullable<int> BUMON_ID { get; set; }
        public Nullable<System.DateTime> INSERT_DATE { get; set; }
        public string INSERT_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<int> DEL_FLAG { get; set; }
    
        public virtual SVR_BUMON SVR_BUMON { get; set; }
        public virtual SVR_COMPANY SVR_COMPANY { get; set; }
    }
}
